### ISSUE TITLE
Switching from test to live.

### ISSUE THREAD

**Issue by archienorman11** [bitpay/bitpay-python#11]
Are there any extra steps apart from changing the bitpay url:

```
API_HOST = "https://bitpay.com" #for production, live bitcoin
# API_HOST = "https://test.bitpay.com" #for testing, testnet bitcoin
```

After the change, I now receive:

`'{"error":"Invalid token"}'`

Am I missing something? 

Thanks,

**Comment by pieterpoorthuis** [comment]
Each environment (test and live) have their own merchant accounts and tokens.
So if you switch from test -> live, you need to redo the pairing process to get a token that's valid for your production BitPay account.

**Comment by archienorman11** [comment]
Hi @pieterpoorthuis  - I generate tokens on the server side, using `/tokens`. 

I have also tried re-generating key files:

```
if os.path.isfile(KEY_FILE):
    print("os.path.isfile(KEY_FILE) == True")
    f = open(KEY_FILE, 'r')
    key = f.read()
    f.close()
    print("Creating a bitpay client using existing private key from disk.")
else:
    print("os.path.isfile(KEY_FILE) == False")
    key = bku.generate_pem()
    print(key)
    f = open(KEY_FILE, 'w')
    print(f)
    f.write(key)
    f.close()
```

**Comment by pieterpoorthuis** [comment]
Are you using the code from /examples/test_merchant_facade.py or examples/test_payouts.py?

Did you also remove the token file from disk?

**Comment by archienorman11** [comment]
I was using payouts and did remove the token file from disk. 
Actually resolved the issue now. The problem was my side, not your API. 
Apologies and thanks for your help.
