### ISSUE TITLE
Headers and Authentication for get_invoice

### ISSUE THREAD

**Issue by pc-coholic** [bitpay/bitpay-python#18]
I am no expert on BitPay by any stretch - but when playing around with this library and the BTCPayServer, I stumbled upon an issue when it comes to picking up the invoice from the BTCPayServer using `get_invoice`:

https://github.com/bitpay/bitpay-python/blob/c26ea8a8ebfaab27065c01ba30edb667f39efc03/bitpay/client.py#L49-L58

This might (or not) be an issue with the library or even with BTCPayServer - so I'll leave this here, open for discussion...

## Headers
Right now, getting an invoice by ID would result in a URI like `https://testnet.demo.btcpayserver.org/invoices/GsX3buFJP3Royg9ZofESv7`. Calling this directly in your webbrowser will redirect to a login-page, using the library will do the same. Ignoring the issue of the login at this point, either we are not being served the expected JSON response, resulting in a `JSONDecodeError`.

I would assume that this is due to the 'accept': `'application/json'`-header. According to the [BitPay API spec](https://bitpay.com/api/#rest-api-resources-invoices-fetch-an-invoice-by-id), `'content-type': 'application/json'` seems to be expected. But since this header was put in in #14, I would assume the original author did this on purpose...

## Authentication for `get_invoice`:
So assuming the above header-issue is fixed, we still don't actually get to see the invoice, since BTCPayServer is not exposing it without authentication. Now this is where I am not sure if BTCPayServer is breaking the API spec which states that during the first 72h of creation, the invoice should be publicly available.

But I would assume that it wouldn't hurt if we did an authenticated call here anyway, 72h-limit or not?

**Comment by anbugal** [comment]
Hi @pc-coholic,

Sorry but this SDKs made by [BitPay](https://bitpay.com) meant to be use with the [BitPay's API](https://bitpay.com/api/). We are not responsible for any other use of it.

To avoid having issues, be welcome to create a BitPay account [here](https://bitpay.com/signup/)
and/or [here](https://test.bitpay.com/signup/) for testing purposes.

**Comment by pc-coholic** [comment]
Hi @anbugal,

I totally understand :-)

But regardless of me not having used the library with the BitPay-server: Could it be that the library is not sending the correct headers, that the API-spec you linked designate as mandatory for `get_invoice`?

If that is the case, I'd be happy to submit a PR to fix that :)

**Comment by anbugal** [comment]
I understand your approach but this SDK is constantly tested and it is stable to work with the BitPay's API. As an open source project, anyone can benefit from it and we are not responsible for non official usages.

Any contribution for improving on how it works with the official BitPay's API will be welcome and very much appreciated.
