### ISSUE TITLE
Maintenance

### ISSUE THREAD

**Issue by Kludex** [bitpay/bitpay-python#25]
I'm about to become a BitPay client, and I found out about this package. I've pondered if I should use this package, and considering the maintenance state and the state of the code itself, I've decided to not use it.

Instead, I've vendored it for my project, and did a clean up (type hint, remove unused code, add missing parameters according to API, small details).

Anyway, I'd like to know if you guys are interested on my improvements. I can open a PR if that's the case. If you guys don't want to waste efforts on this source code, I don't mind receiving maintenance rights, jfyk.

**Comment by anbugal** [comment]
# This repository is no longer maintained and it will be archived by the end of 2021, we are working on a complete new SDK that will be available soon [Here](https://github.com/bitpay/python-bitpay-client)
