### ISSUE TITLE
Pairing code expires and no clear instructions are available on what to do next?

### ISSUE THREAD

**Issue by lanec** [bitpay/bitpay-python#9]
The pairing code offered by BitPay expires after 24 hours.  I see no clear indication of what I do from there.  I get back a 'pos' response from the API when I register using the pairing code but there is a lack of documentation on what this response is and how I use it.  Can you update the library's documentation to include instructions on this?

**Comment by pieterpoorthuis** [comment]
Pairing is the process to connect your local private/public keys to your BitPay merchant account.

During pairing, BitPay generates an API token. The pairing code is used to enable this API token. Once the API token is enabled, you can use it to create BitPay invoices indefinitely. 

The pairing process is described in more detail at https://support.bitpay.com/hc/en-us/articles/115003001183-How-do-I-pair-my-client-and-create-a-token-

**Comment by alfredrumss** [comment]
@pieterpoorthuis  assuming that I'm using server-side pairing. If the pairing code is used once, What place do you recommend do "client.pair_pos_client("MY_CODE_GENERATED_ON_BITPAY_ACCOUNT")" ??

Each time I create invoice I'm doing the pairing process I produce an error because I'm trying to pairing the same code once again. 

Please, help.

**Comment by pieterpoorthuis** [comment]
Alfred,

It's easier to use client-side pairing, using client.create_token(facade). Advantage is that you can use the merchant facade, which gives you more API access rights.

The example in the library will explain your questions in code: https://github.com/bitpay/bitpay-python/blob/master/examples/test_merchant_facade.py

**Comment by alfredrumss** [comment]
@pieterpoorthuis Thank you so much for your Answer.
